### PR TITLE
Works with base 4.13

### PR DESCRIPTION
**Pull request by janvogt**
version bounds increased

### CODE REVIEW

**Comment by ibotty** [comment]
Thank you.  Note, that I don't maintain it anymore.

**Comment by janvogt** [comment]
Thank you for merging then. A pity you don't maintain it anymore. So I'd better look for another IBAN lib or write my own? Do you have any recommendations?

**Comment by ibotty** [comment]
Or you can use that one and mainain it.  I guess there is not much maintenance necessary.

**Comment by janvogt** [comment]
Would be my first public Haskell library and I had to figure how to work with hackage, but I'd be willing to do that.

**Comment by ibotty** [comment]
Yeah, do that!  It's not that hard.  When you have a hackage account, I can grant you the rights to release versions.  I would also give you access to this repository, but you can also use your fork as upstream.

**Comment by janvogt** [comment]
I did sign up for hackage. My account being `jv` I am still waiting though, to hear back from the Hackage Trustees to become member of the uploader group. Regarding the repository: either way works for me. I am leaning to leaving the repo with you, since most of the work is yours...

**Comment by janvogt** [comment]
I've been accepted as Hackage uploader now. You said you could allow me to upload new versions there?

**Pull request merged**
